apiVersion: v1
kind: ServiceAccount
metadata:
  name: alice
  labels:
    app.kubernetes.io/name: dir-client
    app.kubernetes.io/component: alice
---
apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterSPIFFEID
metadata:
  name: alice
  labels:
    app.kubernetes.io/name: dir-client
    app.kubernetes.io/component: alice
spec:
  className: spire-spire
  podSelector:
    matchExpressions:
    - key: app.kubernetes.io/component
      operator: In
      values:
      - alice
  workloadSelectorTemplates:
    - k8s:sa:alice
  spiffeIDTemplate: "spiffe://{{ .TrustDomain }}/ns/default/sa/alice"
  dnsNameTemplates:
    - "alice.dir.svc.cluster.local"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alice-spiffe-config
  labels:
    app.kubernetes.io/name: dir-client
    app.kubernetes.io/component: alice
data:
  helper.conf: |-
    agent_address =  "/run/spire/agent-sockets/api.sock"
    cmd = ""
    cmd_args = ""
    cert_dir = "/svids"
    renew_signal = ""
    svid_file_name = "tls.crt"
    svid_key_file_name = "tls.key"
    svid_bundle_file_name = "svid_bundle.pem"
    jwt_bundle_file_name = "key.jwt"
    cert_file_mode = 0644
    key_file_mode = 0644
    jwt_svid_file_mode = 0644
    jwt_bundle_file_mode = 0644
    jwt_svids = [{jwt_audience="dir-demo", jwt_svid_file_name="jwt_svid.token"}]
    daemon_mode = true
---
apiVersion: v1
kind: Pod
metadata:
  name: alice
  labels:
    app.kubernetes.io/name: dir-client
    app.kubernetes.io/component: alice
spec:
  containers:
  - args:
    - -config
    - config/helper.conf
    image: ghcr.io/spiffe/spiffe-helper:0.10.0
    imagePullPolicy: IfNotPresent
    name: spiffe-helper
    resources: {}
    volumeMounts:
    - mountPath: /config/helper.conf
      name: config-volume
      subPath: helper.conf
    - mountPath: /run/spire/agent-sockets
      name: spire-agent-socket
    - mountPath: /svids
      name: svids-volume
  - command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
    image: ubuntu:latest
    imagePullPolicy: Always
    name: client
    volumeMounts:
    - mountPath: /svids
      name: svids-volume
  restartPolicy: OnFailure
  serviceAccountName: alice
  volumes:
  - hostPath:
      path: /run/spire/agent-sockets
      type: Directory
    name: spire-agent-socket
  - emptyDir: {}
    name: svids-volume
  - configMap:
      defaultMode: 420
      name: alice-spiffe-config
    name: config-volume
