// Copyright AGNTCY Contributors (https://github.com/agntcy)
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: saas/v1alpha1/badge_service.proto

package saasv1alpha1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	BadgeService_CreateBadge_FullMethodName = "/saas.v1alpha1.BadgeService/CreateBadge"
	BadgeService_GetBadge_FullMethodName    = "/saas.v1alpha1.BadgeService/GetBadge"
	BadgeService_DeleteBadge_FullMethodName = "/saas.v1alpha1.BadgeService/DeleteBadge"
)

// BadgeServiceClient is the client API for BadgeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BadgeServiceClient interface {
	CreateBadge(ctx context.Context, in *CreateBadgeRequest, opts ...grpc.CallOption) (*CreateBadgeResponse, error)
	GetBadge(ctx context.Context, in *GetBadgeRequest, opts ...grpc.CallOption) (*GetBadgeResponse, error)
	DeleteBadge(ctx context.Context, in *DeleteBadgeRequest, opts ...grpc.CallOption) (*DeleteBadgeResponse, error)
}

type badgeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBadgeServiceClient(cc grpc.ClientConnInterface) BadgeServiceClient {
	return &badgeServiceClient{cc}
}

func (c *badgeServiceClient) CreateBadge(ctx context.Context, in *CreateBadgeRequest, opts ...grpc.CallOption) (*CreateBadgeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateBadgeResponse)
	err := c.cc.Invoke(ctx, BadgeService_CreateBadge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *badgeServiceClient) GetBadge(ctx context.Context, in *GetBadgeRequest, opts ...grpc.CallOption) (*GetBadgeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBadgeResponse)
	err := c.cc.Invoke(ctx, BadgeService_GetBadge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *badgeServiceClient) DeleteBadge(ctx context.Context, in *DeleteBadgeRequest, opts ...grpc.CallOption) (*DeleteBadgeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteBadgeResponse)
	err := c.cc.Invoke(ctx, BadgeService_DeleteBadge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BadgeServiceServer is the server API for BadgeService service.
// All implementations should embed UnimplementedBadgeServiceServer
// for forward compatibility.
type BadgeServiceServer interface {
	CreateBadge(context.Context, *CreateBadgeRequest) (*CreateBadgeResponse, error)
	GetBadge(context.Context, *GetBadgeRequest) (*GetBadgeResponse, error)
	DeleteBadge(context.Context, *DeleteBadgeRequest) (*DeleteBadgeResponse, error)
}

// UnimplementedBadgeServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBadgeServiceServer struct{}

func (UnimplementedBadgeServiceServer) CreateBadge(context.Context, *CreateBadgeRequest) (*CreateBadgeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBadge not implemented")
}
func (UnimplementedBadgeServiceServer) GetBadge(context.Context, *GetBadgeRequest) (*GetBadgeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBadge not implemented")
}
func (UnimplementedBadgeServiceServer) DeleteBadge(context.Context, *DeleteBadgeRequest) (*DeleteBadgeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBadge not implemented")
}
func (UnimplementedBadgeServiceServer) testEmbeddedByValue() {}

// UnsafeBadgeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BadgeServiceServer will
// result in compilation errors.
type UnsafeBadgeServiceServer interface {
	mustEmbedUnimplementedBadgeServiceServer()
}

func RegisterBadgeServiceServer(s grpc.ServiceRegistrar, srv BadgeServiceServer) {
	// If the following call pancis, it indicates UnimplementedBadgeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BadgeService_ServiceDesc, srv)
}

func _BadgeService_CreateBadge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBadgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BadgeServiceServer).CreateBadge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BadgeService_CreateBadge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BadgeServiceServer).CreateBadge(ctx, req.(*CreateBadgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BadgeService_GetBadge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBadgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BadgeServiceServer).GetBadge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BadgeService_GetBadge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BadgeServiceServer).GetBadge(ctx, req.(*GetBadgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BadgeService_DeleteBadge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBadgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BadgeServiceServer).DeleteBadge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BadgeService_DeleteBadge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BadgeServiceServer).DeleteBadge(ctx, req.(*DeleteBadgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BadgeService_ServiceDesc is the grpc.ServiceDesc for BadgeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BadgeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "saas.v1alpha1.BadgeService",
	HandlerType: (*BadgeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBadge",
			Handler:    _BadgeService_CreateBadge_Handler,
		},
		{
			MethodName: "GetBadge",
			Handler:    _BadgeService_GetBadge_Handler,
		},
		{
			MethodName: "DeleteBadge",
			Handler:    _BadgeService_DeleteBadge_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "saas/v1alpha1/badge_service.proto",
}
