// Copyright AGNTCY Contributors (https://github.com/agntcy)
// SPDX-License-Identifier: Apache-2.0

// @generated by protoc-gen-es v2.9.0 with parameter "import_extension=js"
// @generated from file agntcy/dir/routing/v1/peer.proto (package agntcy.dir.routing.v1, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file agntcy/dir/routing/v1/peer.proto.
 */
export const file_agntcy_dir_routing_v1_peer = /*@__PURE__*/
  fileDesc("CiBhZ250Y3kvZGlyL3JvdXRpbmcvdjEvcGVlci5wcm90bxIVYWdudGN5LmRpci5yb3V0aW5nLnYxItcBCgRQZWVyEgoKAmlkGAEgASgJEg0KBWFkZHJzGAIgAygJEkEKC2Fubm90YXRpb25zGAMgAygLMiwuYWdudGN5LmRpci5yb3V0aW5nLnYxLlBlZXIuQW5ub3RhdGlvbnNFbnRyeRI9Cgpjb25uZWN0aW9uGAQgASgOMikuYWdudGN5LmRpci5yb3V0aW5nLnYxLlBlZXJDb25uZWN0aW9uVHlwZRoyChBBbm5vdGF0aW9uc0VudHJ5EgsKA2tleRgBIAEoCRINCgV2YWx1ZRgCIAEoCToCOAEqrwEKElBlZXJDb25uZWN0aW9uVHlwZRImCiJQRUVSX0NPTk5FQ1RJT05fVFlQRV9OT1RfQ09OTkVDVEVEEAASIgoeUEVFUl9DT05ORUNUSU9OX1RZUEVfQ09OTkVDVEVEEAESJAogUEVFUl9DT05ORUNUSU9OX1RZUEVfQ0FOX0NPTk5FQ1QQAhInCiNQRUVSX0NPTk5FQ1RJT05fVFlQRV9DQU5OT1RfQ09OTkVDVBADQsMBChljb20uYWdudGN5LmRpci5yb3V0aW5nLnYxQglQZWVyUHJvdG9QAVokZ2l0aHViLmNvbS9hZ250Y3kvZGlyL2FwaS9yb3V0aW5nL3YxogIDQURSqgIVQWdudGN5LkRpci5Sb3V0aW5nLlYxygIVQWdudGN5XERpclxSb3V0aW5nXFYx4gIhQWdudGN5XERpclxSb3V0aW5nXFYxXEdQQk1ldGFkYXRh6gIYQWdudGN5OjpEaXI6OlJvdXRpbmc6OlYxYgZwcm90bzM");

/**
 * Describes the message agntcy.dir.routing.v1.Peer.
 * Use `create(PeerSchema)` to create a new message.
 */
export const PeerSchema = /*@__PURE__*/
  messageDesc(file_agntcy_dir_routing_v1_peer, 0);

/**
 * Describes the enum agntcy.dir.routing.v1.PeerConnectionType.
 */
export const PeerConnectionTypeSchema = /*@__PURE__*/
  enumDesc(file_agntcy_dir_routing_v1_peer, 0);

/**
 * @generated from enum agntcy.dir.routing.v1.PeerConnectionType
 */
export const PeerConnectionType = /*@__PURE__*/
  tsEnum(PeerConnectionTypeSchema);

