// Copyright AGNTCY Contributors (https://github.com/agntcy)
// SPDX-License-Identifier: Apache-2.0

// @generated by protoc-gen-es v2.9.0 with parameter "import_extension=js"
// @generated from file agntcy/dir/routing/v1/publication_service.proto (package agntcy.dir.routing.v1, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, serviceDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";
import { file_agntcy_dir_routing_v1_routing_service } from "./routing_service_pb.js";

/**
 * Describes the file agntcy/dir/routing/v1/publication_service.proto.
 */
export const file_agntcy_dir_routing_v1_publication_service = /*@__PURE__*/
  fileDesc("Ci9hZ250Y3kvZGlyL3JvdXRpbmcvdjEvcHVibGljYXRpb25fc2VydmljZS5wcm90bxIVYWdudGN5LmRpci5yb3V0aW5nLnYxIjMKGUNyZWF0ZVB1YmxpY2F0aW9uUmVzcG9uc2USFgoOcHVibGljYXRpb25faWQYASABKAkiVwoXTGlzdFB1YmxpY2F0aW9uc1JlcXVlc3QSEgoFbGltaXQYAiABKA1IAIgBARITCgZvZmZzZXQYAyABKA1IAYgBAUIICgZfbGltaXRCCQoHX29mZnNldCKYAQoUTGlzdFB1YmxpY2F0aW9uc0l0ZW0SFgoOcHVibGljYXRpb25faWQYASABKAkSOAoGc3RhdHVzGAIgASgOMiguYWdudGN5LmRpci5yb3V0aW5nLnYxLlB1YmxpY2F0aW9uU3RhdHVzEhQKDGNyZWF0ZWRfdGltZRgDIAEoCRIYChBsYXN0X3VwZGF0ZV90aW1lGAQgASgJIi8KFUdldFB1YmxpY2F0aW9uUmVxdWVzdBIWCg5wdWJsaWNhdGlvbl9pZBgBIAEoCSKaAQoWR2V0UHVibGljYXRpb25SZXNwb25zZRIWCg5wdWJsaWNhdGlvbl9pZBgBIAEoCRI4CgZzdGF0dXMYAiABKA4yKC5hZ250Y3kuZGlyLnJvdXRpbmcudjEuUHVibGljYXRpb25TdGF0dXMSFAoMY3JlYXRlZF90aW1lGAMgASgJEhgKEGxhc3RfdXBkYXRlX3RpbWUYBCABKAkqvAEKEVB1YmxpY2F0aW9uU3RhdHVzEiIKHlBVQkxJQ0FUSU9OX1NUQVRVU19VTlNQRUNJRklFRBAAEh4KGlBVQkxJQ0FUSU9OX1NUQVRVU19QRU5ESU5HEAESIgoeUFVCTElDQVRJT05fU1RBVFVTX0lOX1BST0dSRVNTEAISIAocUFVCTElDQVRJT05fU1RBVFVTX0NPTVBMRVRFRBADEh0KGVBVQkxJQ0FUSU9OX1NUQVRVU19GQUlMRUQQBDLkAgoSUHVibGljYXRpb25TZXJ2aWNlEmwKEUNyZWF0ZVB1YmxpY2F0aW9uEiUuYWdudGN5LmRpci5yb3V0aW5nLnYxLlB1Ymxpc2hSZXF1ZXN0GjAuYWdudGN5LmRpci5yb3V0aW5nLnYxLkNyZWF0ZVB1YmxpY2F0aW9uUmVzcG9uc2UScQoQTGlzdFB1YmxpY2F0aW9ucxIuLmFnbnRjeS5kaXIucm91dGluZy52MS5MaXN0UHVibGljYXRpb25zUmVxdWVzdBorLmFnbnRjeS5kaXIucm91dGluZy52MS5MaXN0UHVibGljYXRpb25zSXRlbTABEm0KDkdldFB1YmxpY2F0aW9uEiwuYWdudGN5LmRpci5yb3V0aW5nLnYxLkdldFB1YmxpY2F0aW9uUmVxdWVzdBotLmFnbnRjeS5kaXIucm91dGluZy52MS5HZXRQdWJsaWNhdGlvblJlc3BvbnNlQtEBChljb20uYWdudGN5LmRpci5yb3V0aW5nLnYxQhdQdWJsaWNhdGlvblNlcnZpY2VQcm90b1ABWiRnaXRodWIuY29tL2FnbnRjeS9kaXIvYXBpL3JvdXRpbmcvdjGiAgNBRFKqAhVBZ250Y3kuRGlyLlJvdXRpbmcuVjHKAhVBZ250Y3lcRGlyXFJvdXRpbmdcVjHiAiFBZ250Y3lcRGlyXFJvdXRpbmdcVjFcR1BCTWV0YWRhdGHqAhhBZ250Y3k6OkRpcjo6Um91dGluZzo6VjFiBnByb3RvMw", [file_agntcy_dir_routing_v1_routing_service]);

/**
 * Describes the message agntcy.dir.routing.v1.CreatePublicationResponse.
 * Use `create(CreatePublicationResponseSchema)` to create a new message.
 */
export const CreatePublicationResponseSchema = /*@__PURE__*/
  messageDesc(file_agntcy_dir_routing_v1_publication_service, 0);

/**
 * Describes the message agntcy.dir.routing.v1.ListPublicationsRequest.
 * Use `create(ListPublicationsRequestSchema)` to create a new message.
 */
export const ListPublicationsRequestSchema = /*@__PURE__*/
  messageDesc(file_agntcy_dir_routing_v1_publication_service, 1);

/**
 * Describes the message agntcy.dir.routing.v1.ListPublicationsItem.
 * Use `create(ListPublicationsItemSchema)` to create a new message.
 */
export const ListPublicationsItemSchema = /*@__PURE__*/
  messageDesc(file_agntcy_dir_routing_v1_publication_service, 2);

/**
 * Describes the message agntcy.dir.routing.v1.GetPublicationRequest.
 * Use `create(GetPublicationRequestSchema)` to create a new message.
 */
export const GetPublicationRequestSchema = /*@__PURE__*/
  messageDesc(file_agntcy_dir_routing_v1_publication_service, 3);

/**
 * Describes the message agntcy.dir.routing.v1.GetPublicationResponse.
 * Use `create(GetPublicationResponseSchema)` to create a new message.
 */
export const GetPublicationResponseSchema = /*@__PURE__*/
  messageDesc(file_agntcy_dir_routing_v1_publication_service, 4);

/**
 * Describes the enum agntcy.dir.routing.v1.PublicationStatus.
 */
export const PublicationStatusSchema = /*@__PURE__*/
  enumDesc(file_agntcy_dir_routing_v1_publication_service, 0);

/**
 * PublicationStatus represents the current state of a publication request.
 * Publications progress from pending to processing to completed or failed states.
 *
 * @generated from enum agntcy.dir.routing.v1.PublicationStatus
 */
export const PublicationStatus = /*@__PURE__*/
  tsEnum(PublicationStatusSchema);

/**
 * PublicationService manages publication requests for announcing records to the DHT.
 *
 * Publications are stored in the database and processed by a worker that runs every hour.
 * The publication workflow:
 * 1. Publications are created via routing's Publish RPC by specifying either a query, a list of CIDs, or all records
 * 2. Publication requests are added to the database
 * 3. PublicationWorker queries the data using the publication request from the database to get the list of CIDs to be published
 * 4. PublicationWorker announces the records with these CIDs to the DHT
 *
 * @generated from service agntcy.dir.routing.v1.PublicationService
 */
export const PublicationService = /*@__PURE__*/
  serviceDesc(file_agntcy_dir_routing_v1_publication_service, 0);

