// Copyright AGNTCY Contributors (https://github.com/agntcy)
// SPDX-License-Identifier: Apache-2.0

// @generated by protoc-gen-es v2.9.0 with parameter "import_extension=js"
// @generated from file agntcy/dir/routing/v1/record_query.proto (package agntcy.dir.routing.v1, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file agntcy/dir/routing/v1/record_query.proto.
 */
export const file_agntcy_dir_routing_v1_record_query = /*@__PURE__*/
  fileDesc("CihhZ250Y3kvZGlyL3JvdXRpbmcvdjEvcmVjb3JkX3F1ZXJ5LnByb3RvEhVhZ250Y3kuZGlyLnJvdXRpbmcudjEiUgoLUmVjb3JkUXVlcnkSNAoEdHlwZRgBIAEoDjImLmFnbnRjeS5kaXIucm91dGluZy52MS5SZWNvcmRRdWVyeVR5cGUSDQoFdmFsdWUYAiABKAkqrAEKD1JlY29yZFF1ZXJ5VHlwZRIhCh1SRUNPUkRfUVVFUllfVFlQRV9VTlNQRUNJRklFRBAAEhsKF1JFQ09SRF9RVUVSWV9UWVBFX1NLSUxMEAESHQoZUkVDT1JEX1FVRVJZX1RZUEVfTE9DQVRPUhACEhwKGFJFQ09SRF9RVUVSWV9UWVBFX0RPTUFJThADEhwKGFJFQ09SRF9RVUVSWV9UWVBFX01PRFVMRRAEQsoBChljb20uYWdudGN5LmRpci5yb3V0aW5nLnYxQhBSZWNvcmRRdWVyeVByb3RvUAFaJGdpdGh1Yi5jb20vYWdudGN5L2Rpci9hcGkvcm91dGluZy92MaICA0FEUqoCFUFnbnRjeS5EaXIuUm91dGluZy5WMcoCFUFnbnRjeVxEaXJcUm91dGluZ1xWMeICIUFnbnRjeVxEaXJcUm91dGluZ1xWMVxHUEJNZXRhZGF0YeoCGEFnbnRjeTo6RGlyOjpSb3V0aW5nOjpWMWIGcHJvdG8z");

/**
 * Describes the message agntcy.dir.routing.v1.RecordQuery.
 * Use `create(RecordQuerySchema)` to create a new message.
 */
export const RecordQuerySchema = /*@__PURE__*/
  messageDesc(file_agntcy_dir_routing_v1_record_query, 0);

/**
 * Describes the enum agntcy.dir.routing.v1.RecordQueryType.
 */
export const RecordQueryTypeSchema = /*@__PURE__*/
  enumDesc(file_agntcy_dir_routing_v1_record_query, 0);

/**
 * Defines a list of supported record query types.
 *
 * @generated from enum agntcy.dir.routing.v1.RecordQueryType
 */
export const RecordQueryType = /*@__PURE__*/
  tsEnum(RecordQueryTypeSchema);

