// Copyright AGNTCY Contributors (https://github.com/agntcy)
// SPDX-License-Identifier: Apache-2.0

// @generated by protoc-gen-es v2.9.0 with parameter "import_extension=js"
// @generated from file agntcy/dir/routing/v1/record_query.proto (package agntcy.dir.routing.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file agntcy/dir/routing/v1/record_query.proto.
 */
export declare const file_agntcy_dir_routing_v1_record_query: GenFile;

/**
 * A query to match the record against during discovery.
 * For example:
 *  { type: RECORD_QUERY_TYPE_SKILL, value: "Natural Language Processing" }
 *  { type: RECORD_QUERY_TYPE_LOCATOR, value: "helm-chart" }
 *  { type: RECORD_QUERY_TYPE_DOMAIN, value: "research" }
 *  { type: RECORD_QUERY_TYPE_MODULE, value: "runtime/language" }
 *
 * @generated from message agntcy.dir.routing.v1.RecordQuery
 */
export declare type RecordQuery = Message<"agntcy.dir.routing.v1.RecordQuery"> & {
  /**
   * The type of the query to match against.
   *
   * @generated from field: agntcy.dir.routing.v1.RecordQueryType type = 1;
   */
  type: RecordQueryType;

  /**
   * The query value to match against.
   *
   * @generated from field: string value = 2;
   */
  value: string;
};

/**
 * Describes the message agntcy.dir.routing.v1.RecordQuery.
 * Use `create(RecordQuerySchema)` to create a new message.
 */
export declare const RecordQuerySchema: GenMessage<RecordQuery>;

/**
 * Defines a list of supported record query types.
 *
 * @generated from enum agntcy.dir.routing.v1.RecordQueryType
 */
export enum RecordQueryType {
  /**
   * Unspecified query type.
   *
   * @generated from enum value: RECORD_QUERY_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Query for a skill name.
   *
   * @generated from enum value: RECORD_QUERY_TYPE_SKILL = 1;
   */
  SKILL = 1,

  /**
   * Query for a locator type.
   *
   * @generated from enum value: RECORD_QUERY_TYPE_LOCATOR = 2;
   */
  LOCATOR = 2,

  /**
   * Query for a domain name.
   *
   * @generated from enum value: RECORD_QUERY_TYPE_DOMAIN = 3;
   */
  DOMAIN = 3,

  /**
   * Query for a module name.
   *
   * @generated from enum value: RECORD_QUERY_TYPE_MODULE = 4;
   */
  MODULE = 4,
}

/**
 * Describes the enum agntcy.dir.routing.v1.RecordQueryType.
 */
export declare const RecordQueryTypeSchema: GenEnum<RecordQueryType>;

