// Copyright AGNTCY Contributors (https://github.com/agntcy)
// SPDX-License-Identifier: Apache-2.0

// @generated by protoc-gen-es v2.9.0 with parameter "import_extension=js"
// @generated from file agntcy/dir/core/v1/record.proto (package agntcy.dir.core.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_struct } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file agntcy/dir/core/v1/record.proto.
 */
export const file_agntcy_dir_core_v1_record = /*@__PURE__*/
  fileDesc("Ch9hZ250Y3kvZGlyL2NvcmUvdjEvcmVjb3JkLnByb3RvEhJhZ250Y3kuZGlyLmNvcmUudjEiGAoJUmVjb3JkUmVmEgsKA2NpZBgBIAEoCSK/AQoKUmVjb3JkTWV0YRILCgNjaWQYASABKAkSRAoLYW5ub3RhdGlvbnMYAiADKAsyLy5hZ250Y3kuZGlyLmNvcmUudjEuUmVjb3JkTWV0YS5Bbm5vdGF0aW9uc0VudHJ5EhYKDnNjaGVtYV92ZXJzaW9uGAMgASgJEhIKCmNyZWF0ZWRfYXQYBCABKAkaMgoQQW5ub3RhdGlvbnNFbnRyeRILCgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAk6AjgBIi8KBlJlY29yZBIlCgRkYXRhGAEgASgLMhcuZ29vZ2xlLnByb3RvYnVmLlN0cnVjdCKKAgoOUmVjb3JkUmVmZXJyZXISDAoEdHlwZRgBIAEoCRIxCgpyZWNvcmRfcmVmGAIgASgLMh0uYWdudGN5LmRpci5jb3JlLnYxLlJlY29yZFJlZhJICgthbm5vdGF0aW9ucxgDIAMoCzIzLmFnbnRjeS5kaXIuY29yZS52MS5SZWNvcmRSZWZlcnJlci5Bbm5vdGF0aW9uc0VudHJ5EhIKCmNyZWF0ZWRfYXQYBCABKAkSJQoEZGF0YRgFIAEoCzIXLmdvb2dsZS5wcm90b2J1Zi5TdHJ1Y3QaMgoQQW5ub3RhdGlvbnNFbnRyeRILCgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAk6AjgBQrMBChZjb20uYWdudGN5LmRpci5jb3JlLnYxQgtSZWNvcmRQcm90b1ABWiFnaXRodWIuY29tL2FnbnRjeS9kaXIvYXBpL2NvcmUvdjGiAgNBREOqAhJBZ250Y3kuRGlyLkNvcmUuVjHKAhJBZ250Y3lcRGlyXENvcmVcVjHiAh5BZ250Y3lcRGlyXENvcmVcVjFcR1BCTWV0YWRhdGHqAhVBZ250Y3k6OkRpcjo6Q29yZTo6VjFiBnByb3RvMw", [file_google_protobuf_struct]);

/**
 * Describes the message agntcy.dir.core.v1.RecordRef.
 * Use `create(RecordRefSchema)` to create a new message.
 */
export const RecordRefSchema = /*@__PURE__*/
  messageDesc(file_agntcy_dir_core_v1_record, 0);

/**
 * Describes the message agntcy.dir.core.v1.RecordMeta.
 * Use `create(RecordMetaSchema)` to create a new message.
 */
export const RecordMetaSchema = /*@__PURE__*/
  messageDesc(file_agntcy_dir_core_v1_record, 1);

/**
 * Describes the message agntcy.dir.core.v1.Record.
 * Use `create(RecordSchema)` to create a new message.
 */
export const RecordSchema = /*@__PURE__*/
  messageDesc(file_agntcy_dir_core_v1_record, 2);

/**
 * Describes the message agntcy.dir.core.v1.RecordReferrer.
 * Use `create(RecordReferrerSchema)` to create a new message.
 */
export const RecordReferrerSchema = /*@__PURE__*/
  messageDesc(file_agntcy_dir_core_v1_record, 3);

