// Copyright AGNTCY Contributors (https://github.com/agntcy)
// SPDX-License-Identifier: Apache-2.0

// @generated by protoc-gen-es v2.9.0 with parameter "import_extension=js"
// @generated from file agntcy/dir/events/v1/event_service.proto (package agntcy.dir.events.v1, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, serviceDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file agntcy/dir/events/v1/event_service.proto.
 */
export const file_agntcy_dir_events_v1_event_service = /*@__PURE__*/
  fileDesc("CihhZ250Y3kvZGlyL2V2ZW50cy92MS9ldmVudF9zZXJ2aWNlLnByb3RvEhRhZ250Y3kuZGlyLmV2ZW50cy52MSJxCg1MaXN0ZW5SZXF1ZXN0EjQKC2V2ZW50X3R5cGVzGAEgAygOMh8uYWdudGN5LmRpci5ldmVudHMudjEuRXZlbnRUeXBlEhUKDWxhYmVsX2ZpbHRlcnMYAiADKAkSEwoLY2lkX2ZpbHRlcnMYAyADKAkiPAoOTGlzdGVuUmVzcG9uc2USKgoFZXZlbnQYASABKAsyGy5hZ250Y3kuZGlyLmV2ZW50cy52MS5FdmVudCKEAgoFRXZlbnQSCgoCaWQYASABKAkSLQoEdHlwZRgCIAEoDjIfLmFnbnRjeS5kaXIuZXZlbnRzLnYxLkV2ZW50VHlwZRItCgl0aW1lc3RhbXAYAyABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEhMKC3Jlc291cmNlX2lkGAQgASgJEg4KBmxhYmVscxgFIAMoCRI7CghtZXRhZGF0YRgHIAMoCzIpLmFnbnRjeS5kaXIuZXZlbnRzLnYxLkV2ZW50Lk1ldGFkYXRhRW50cnkaLwoNTWV0YWRhdGFFbnRyeRILCgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAk6AjgBKrwCCglFdmVudFR5cGUSGgoWRVZFTlRfVFlQRV9VTlNQRUNJRklFRBAAEhwKGEVWRU5UX1RZUEVfUkVDT1JEX1BVU0hFRBABEhwKGEVWRU5UX1RZUEVfUkVDT1JEX1BVTExFRBACEh0KGUVWRU5UX1RZUEVfUkVDT1JEX0RFTEVURUQQAxIfChtFVkVOVF9UWVBFX1JFQ09SRF9QVUJMSVNIRUQQBBIhCh1FVkVOVF9UWVBFX1JFQ09SRF9VTlBVQkxJU0hFRBAFEhsKF0VWRU5UX1RZUEVfU1lOQ19DUkVBVEVEEAYSHQoZRVZFTlRfVFlQRV9TWU5DX0NPTVBMRVRFRBAHEhoKFkVWRU5UX1RZUEVfU1lOQ19GQUlMRUQQCBIcChhFVkVOVF9UWVBFX1JFQ09SRF9TSUdORUQQCTJlCgxFdmVudFNlcnZpY2USVQoGTGlzdGVuEiMuYWdudGN5LmRpci5ldmVudHMudjEuTGlzdGVuUmVxdWVzdBokLmFnbnRjeS5kaXIuZXZlbnRzLnYxLkxpc3RlblJlc3BvbnNlMAFCxQEKGGNvbS5hZ250Y3kuZGlyLmV2ZW50cy52MUIRRXZlbnRTZXJ2aWNlUHJvdG9QAVojZ2l0aHViLmNvbS9hZ250Y3kvZGlyL2FwaS9ldmVudHMvdjGiAgNBREWqAhRBZ250Y3kuRGlyLkV2ZW50cy5WMcoCFEFnbnRjeVxEaXJcRXZlbnRzXFYx4gIgQWdudGN5XERpclxFdmVudHNcVjFcR1BCTWV0YWRhdGHqAhdBZ250Y3k6OkRpcjo6RXZlbnRzOjpWMWIGcHJvdG8z", [file_google_protobuf_timestamp]);

/**
 * Describes the message agntcy.dir.events.v1.ListenRequest.
 * Use `create(ListenRequestSchema)` to create a new message.
 */
export const ListenRequestSchema = /*@__PURE__*/
  messageDesc(file_agntcy_dir_events_v1_event_service, 0);

/**
 * Describes the message agntcy.dir.events.v1.ListenResponse.
 * Use `create(ListenResponseSchema)` to create a new message.
 */
export const ListenResponseSchema = /*@__PURE__*/
  messageDesc(file_agntcy_dir_events_v1_event_service, 1);

/**
 * Describes the message agntcy.dir.events.v1.Event.
 * Use `create(EventSchema)` to create a new message.
 */
export const EventSchema = /*@__PURE__*/
  messageDesc(file_agntcy_dir_events_v1_event_service, 2);

/**
 * Describes the enum agntcy.dir.events.v1.EventType.
 */
export const EventTypeSchema = /*@__PURE__*/
  enumDesc(file_agntcy_dir_events_v1_event_service, 0);

/**
 * EventType represents all valid event types in the system.
 * Each value represents a specific operation that can occur.
 *
 * Supported Events:
 * - Store: RECORD_PUSHED, RECORD_PULLED, RECORD_DELETED
 * - Routing: RECORD_PUBLISHED, RECORD_UNPUBLISHED
 * - Sync: SYNC_CREATED, SYNC_COMPLETED, SYNC_FAILED
 * - Sign: RECORD_SIGNED
 *
 * @generated from enum agntcy.dir.events.v1.EventType
 */
export const EventType = /*@__PURE__*/
  tsEnum(EventTypeSchema);

/**
 * EventService provides real-time event streaming for all system operations.
 * Events are delivered from subscription time forward with no history or replay.
 * This service enables external applications to react to system changes in real-time.
 *
 * @generated from service agntcy.dir.events.v1.EventService
 */
export const EventService = /*@__PURE__*/
  serviceDesc(file_agntcy_dir_events_v1_event_service, 0);

