// Copyright AGNTCY Contributors (https://github.com/agntcy)
// SPDX-License-Identifier: Apache-2.0

// @generated by protoc-gen-es v2.9.0 with parameter "import_extension=js"
// @generated from file agntcy/dir/search/v1/record_query.proto (package agntcy.dir.search.v1, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file agntcy/dir/search/v1/record_query.proto.
 */
export const file_agntcy_dir_search_v1_record_query = /*@__PURE__*/
  fileDesc("CidhZ250Y3kvZGlyL3NlYXJjaC92MS9yZWNvcmRfcXVlcnkucHJvdG8SFGFnbnRjeS5kaXIuc2VhcmNoLnYxIlEKC1JlY29yZFF1ZXJ5EjMKBHR5cGUYASABKA4yJS5hZ250Y3kuZGlyLnNlYXJjaC52MS5SZWNvcmRRdWVyeVR5cGUSDQoFdmFsdWUYAiABKAkqsgIKD1JlY29yZFF1ZXJ5VHlwZRIhCh1SRUNPUkRfUVVFUllfVFlQRV9VTlNQRUNJRklFRBAAEhoKFlJFQ09SRF9RVUVSWV9UWVBFX05BTUUQARIdChlSRUNPUkRfUVVFUllfVFlQRV9WRVJTSU9OEAISHgoaUkVDT1JEX1FVRVJZX1RZUEVfU0tJTExfSUQQAxIgChxSRUNPUkRfUVVFUllfVFlQRV9TS0lMTF9OQU1FEAQSHQoZUkVDT1JEX1FVRVJZX1RZUEVfTE9DQVRPUhAFEhwKGFJFQ09SRF9RVUVSWV9UWVBFX01PRFVMRRAGEh8KG1JFQ09SRF9RVUVSWV9UWVBFX0RPTUFJTl9JRBAHEiEKHVJFQ09SRF9RVUVSWV9UWVBFX0RPTUFJTl9OQU1FEAhCxAEKGGNvbS5hZ250Y3kuZGlyLnNlYXJjaC52MUIQUmVjb3JkUXVlcnlQcm90b1ABWiNnaXRodWIuY29tL2FnbnRjeS9kaXIvYXBpL3NlYXJjaC92MaICA0FEU6oCFEFnbnRjeS5EaXIuU2VhcmNoLlYxygIUQWdudGN5XERpclxTZWFyY2hcVjHiAiBBZ250Y3lcRGlyXFNlYXJjaFxWMVxHUEJNZXRhZGF0YeoCF0FnbnRjeTo6RGlyOjpTZWFyY2g6OlYxYgZwcm90bzM");

/**
 * Describes the message agntcy.dir.search.v1.RecordQuery.
 * Use `create(RecordQuerySchema)` to create a new message.
 */
export const RecordQuerySchema = /*@__PURE__*/
  messageDesc(file_agntcy_dir_search_v1_record_query, 0);

/**
 * Describes the enum agntcy.dir.search.v1.RecordQueryType.
 */
export const RecordQueryTypeSchema = /*@__PURE__*/
  enumDesc(file_agntcy_dir_search_v1_record_query, 0);

/**
 * Defines a list of supported record query types.
 *
 * @generated from enum agntcy.dir.search.v1.RecordQueryType
 */
export const RecordQueryType = /*@__PURE__*/
  tsEnum(RecordQueryTypeSchema);

