// Copyright AGNTCY Contributors (https://github.com/agntcy)
// SPDX-License-Identifier: Apache-2.0

// @generated by protoc-gen-es v2.9.0 with parameter "import_extension=js"
// @generated from file agntcy/dir/search/v1/search_service.proto (package agntcy.dir.search.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { RecordQuery } from "./record_query_pb.js";

/**
 * Describes the file agntcy/dir/search/v1/search_service.proto.
 */
export declare const file_agntcy_dir_search_v1_search_service: GenFile;

/**
 * @generated from message agntcy.dir.search.v1.SearchRequest
 */
export declare type SearchRequest = Message<"agntcy.dir.search.v1.SearchRequest"> & {
  /**
   * List of queries to match against the records.
   *
   * @generated from field: repeated agntcy.dir.search.v1.RecordQuery queries = 1;
   */
  queries: RecordQuery[];

  /**
   * Optional limit on the number of results to return.
   *
   * @generated from field: optional uint32 limit = 2;
   */
  limit?: number;

  /**
   * Optional offset for pagination of results.
   *
   * @generated from field: optional uint32 offset = 3;
   */
  offset?: number;
};

/**
 * Describes the message agntcy.dir.search.v1.SearchRequest.
 * Use `create(SearchRequestSchema)` to create a new message.
 */
export declare const SearchRequestSchema: GenMessage<SearchRequest>;

/**
 * @generated from message agntcy.dir.search.v1.SearchResponse
 */
export declare type SearchResponse = Message<"agntcy.dir.search.v1.SearchResponse"> & {
  /**
   * The CID of the record that matches the search criteria.
   *
   * @generated from field: string record_cid = 1;
   */
  recordCid: string;
};

/**
 * Describes the message agntcy.dir.search.v1.SearchResponse.
 * Use `create(SearchResponseSchema)` to create a new message.
 */
export declare const SearchResponseSchema: GenMessage<SearchResponse>;

/**
 * @generated from service agntcy.dir.search.v1.SearchService
 */
export declare const SearchService: GenService<{
  /**
   * List records that this peer is currently providing that match the given parameters.
   * This operation does not interact with the network.
   *
   * @generated from rpc agntcy.dir.search.v1.SearchService.Search
   */
  search: {
    methodKind: "server_streaming";
    input: typeof SearchRequestSchema;
    output: typeof SearchResponseSchema;
  },
}>;

