// Copyright AGNTCY Contributors (https://github.com/agntcy)
// SPDX-License-Identifier: Apache-2.0

// @generated by protoc-gen-es v2.9.0 with parameter "import_extension=js"
// @generated from file agntcy/dir/sign/v1/public_key.proto (package agntcy.dir.sign.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file agntcy/dir/sign/v1/public_key.proto.
 */
export declare const file_agntcy_dir_sign_v1_public_key: GenFile;

/**
 * PublicKey is the public key data associated with a Record.
 * Multiple public keys can be associated with a single Record.
 *
 * @generated from message agntcy.dir.sign.v1.PublicKey
 */
export declare type PublicKey = Message<"agntcy.dir.sign.v1.PublicKey"> & {
  /**
   * PEM-encoded public key string.
   *
   * @generated from field: string key = 1;
   */
  key: string;
};

/**
 * Describes the message agntcy.dir.sign.v1.PublicKey.
 * Use `create(PublicKeySchema)` to create a new message.
 */
export declare const PublicKeySchema: GenMessage<PublicKey>;

