// Copyright AGNTCY Contributors (https://github.com/agntcy)
// SPDX-License-Identifier: Apache-2.0

// @generated by protoc-gen-es v2.9.0 with parameter "import_extension=js"
// @generated from file agntcy/dir/sign/v1/public_key.proto (package agntcy.dir.sign.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file agntcy/dir/sign/v1/public_key.proto.
 */
export const file_agntcy_dir_sign_v1_public_key = /*@__PURE__*/
  fileDesc("CiNhZ250Y3kvZGlyL3NpZ24vdjEvcHVibGljX2tleS5wcm90bxISYWdudGN5LmRpci5zaWduLnYxIhgKCVB1YmxpY0tleRILCgNrZXkYASABKAlCtgEKFmNvbS5hZ250Y3kuZGlyLnNpZ24udjFCDlB1YmxpY0tleVByb3RvUAFaIWdpdGh1Yi5jb20vYWdudGN5L2Rpci9hcGkvc2lnbi92MaICA0FEU6oCEkFnbnRjeS5EaXIuU2lnbi5WMcoCEkFnbnRjeVxEaXJcU2lnblxWMeICHkFnbnRjeVxEaXJcU2lnblxWMVxHUEJNZXRhZGF0YeoCFUFnbnRjeTo6RGlyOjpTaWduOjpWMWIGcHJvdG8z");

/**
 * Describes the message agntcy.dir.sign.v1.PublicKey.
 * Use `create(PublicKeySchema)` to create a new message.
 */
export const PublicKeySchema = /*@__PURE__*/
  messageDesc(file_agntcy_dir_sign_v1_public_key, 0);

