// Copyright AGNTCY Contributors (https://github.com/agntcy)
// SPDX-License-Identifier: Apache-2.0

// @generated by protoc-gen-es v2.9.0 with parameter "import_extension=js"
// @generated from file agntcy/dir/sign/v1/signature.proto (package agntcy.dir.sign.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file agntcy/dir/sign/v1/signature.proto.
 */
export const file_agntcy_dir_sign_v1_signature = /*@__PURE__*/
  fileDesc("CiJhZ250Y3kvZGlyL3NpZ24vdjEvc2lnbmF0dXJlLnByb3RvEhJhZ250Y3kuZGlyLnNpZ24udjEigAIKCVNpZ25hdHVyZRJDCgthbm5vdGF0aW9ucxgBIAMoCzIuLmFnbnRjeS5kaXIuc2lnbi52MS5TaWduYXR1cmUuQW5ub3RhdGlvbnNFbnRyeRIRCglzaWduZWRfYXQYAiABKAkSEQoJYWxnb3JpdGhtGAMgASgJEhEKCXNpZ25hdHVyZRgEIAEoCRITCgtjZXJ0aWZpY2F0ZRgFIAEoCRIUCgxjb250ZW50X3R5cGUYBiABKAkSFgoOY29udGVudF9idW5kbGUYByABKAkaMgoQQW5ub3RhdGlvbnNFbnRyeRILCgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAk6AjgBQrYBChZjb20uYWdudGN5LmRpci5zaWduLnYxQg5TaWduYXR1cmVQcm90b1ABWiFnaXRodWIuY29tL2FnbnRjeS9kaXIvYXBpL3NpZ24vdjGiAgNBRFOqAhJBZ250Y3kuRGlyLlNpZ24uVjHKAhJBZ250Y3lcRGlyXFNpZ25cVjHiAh5BZ250Y3lcRGlyXFNpZ25cVjFcR1BCTWV0YWRhdGHqAhVBZ250Y3k6OkRpcjo6U2lnbjo6VjFiBnByb3RvMw");

/**
 * Describes the message agntcy.dir.sign.v1.Signature.
 * Use `create(SignatureSchema)` to create a new message.
 */
export const SignatureSchema = /*@__PURE__*/
  messageDesc(file_agntcy_dir_sign_v1_signature, 0);

