// Copyright AGNTCY Contributors (https://github.com/agntcy)
// SPDX-License-Identifier: Apache-2.0

// @generated by protoc-gen-es v2.9.0 with parameter "import_extension=js"
// @generated from file agntcy/dir/sign/v1/sign_service.proto (package agntcy.dir.sign.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_agntcy_dir_core_v1_record } from "../../core/v1/record_pb.js";
import { file_agntcy_dir_sign_v1_signature } from "./signature_pb.js";

/**
 * Describes the file agntcy/dir/sign/v1/sign_service.proto.
 */
export const file_agntcy_dir_sign_v1_sign_service = /*@__PURE__*/
  fileDesc("CiVhZ250Y3kvZGlyL3NpZ24vdjEvc2lnbl9zZXJ2aWNlLnByb3RvEhJhZ250Y3kuZGlyLnNpZ24udjEiewoLU2lnblJlcXVlc3QSMQoKcmVjb3JkX3JlZhgBIAEoCzIdLmFnbnRjeS5kaXIuY29yZS52MS5SZWNvcmRSZWYSOQoIcHJvdmlkZXIYAiABKAsyJy5hZ250Y3kuZGlyLnNpZ24udjEuU2lnblJlcXVlc3RQcm92aWRlciKCAQoTU2lnblJlcXVlc3RQcm92aWRlchIwCgRvaWRjGAEgASgLMiAuYWdudGN5LmRpci5zaWduLnYxLlNpZ25XaXRoT0lEQ0gAEi4KA2tleRgCIAEoCzIfLmFnbnRjeS5kaXIuc2lnbi52MS5TaWduV2l0aEtleUgAQgkKB3JlcXVlc3QimwIKDFNpZ25XaXRoT0lEQxIQCghpZF90b2tlbhgBIAEoCRI6CgdvcHRpb25zGAIgASgLMikuYWdudGN5LmRpci5zaWduLnYxLlNpZ25XaXRoT0lEQy5TaWduT3B0cxq8AQoIU2lnbk9wdHMSFwoKZnVsY2lvX3VybBgBIAEoCUgAiAEBEhYKCXJla29yX3VybBgCIAEoCUgBiAEBEhoKDXRpbWVzdGFtcF91cmwYAyABKAlIAogBARIeChFvaWRjX3Byb3ZpZGVyX3VybBgEIAEoCUgDiAEBQg0KC19mdWxjaW9fdXJsQgwKCl9yZWtvcl91cmxCEAoOX3RpbWVzdGFtcF91cmxCFAoSX29pZGNfcHJvdmlkZXJfdXJsIkYKC1NpZ25XaXRoS2V5EhMKC3ByaXZhdGVfa2V5GAEgASgMEhUKCHBhc3N3b3JkGAIgASgMSACIAQFCCwoJX3Bhc3N3b3JkIkAKDFNpZ25SZXNwb25zZRIwCglzaWduYXR1cmUYASABKAsyHS5hZ250Y3kuZGlyLnNpZ24udjEuU2lnbmF0dXJlIkIKDVZlcmlmeVJlcXVlc3QSMQoKcmVjb3JkX3JlZhgBIAEoCzIdLmFnbnRjeS5kaXIuY29yZS52MS5SZWNvcmRSZWYiTwoOVmVyaWZ5UmVzcG9uc2USDwoHc3VjY2VzcxgBIAEoCBIaCg1lcnJvcl9tZXNzYWdlGAIgASgJSACIAQFCEAoOX2Vycm9yX21lc3NhZ2UyqQEKC1NpZ25TZXJ2aWNlEkkKBFNpZ24SHy5hZ250Y3kuZGlyLnNpZ24udjEuU2lnblJlcXVlc3QaIC5hZ250Y3kuZGlyLnNpZ24udjEuU2lnblJlc3BvbnNlEk8KBlZlcmlmeRIhLmFnbnRjeS5kaXIuc2lnbi52MS5WZXJpZnlSZXF1ZXN0GiIuYWdudGN5LmRpci5zaWduLnYxLlZlcmlmeVJlc3BvbnNlQrgBChZjb20uYWdudGN5LmRpci5zaWduLnYxQhBTaWduU2VydmljZVByb3RvUAFaIWdpdGh1Yi5jb20vYWdudGN5L2Rpci9hcGkvc2lnbi92MaICA0FEU6oCEkFnbnRjeS5EaXIuU2lnbi5WMcoCEkFnbnRjeVxEaXJcU2lnblxWMeICHkFnbnRjeVxEaXJcU2lnblxWMVxHUEJNZXRhZGF0YeoCFUFnbnRjeTo6RGlyOjpTaWduOjpWMWIGcHJvdG8z", [file_agntcy_dir_core_v1_record, file_agntcy_dir_sign_v1_signature]);

/**
 * Describes the message agntcy.dir.sign.v1.SignRequest.
 * Use `create(SignRequestSchema)` to create a new message.
 */
export const SignRequestSchema = /*@__PURE__*/
  messageDesc(file_agntcy_dir_sign_v1_sign_service, 0);

/**
 * Describes the message agntcy.dir.sign.v1.SignRequestProvider.
 * Use `create(SignRequestProviderSchema)` to create a new message.
 */
export const SignRequestProviderSchema = /*@__PURE__*/
  messageDesc(file_agntcy_dir_sign_v1_sign_service, 1);

/**
 * Describes the message agntcy.dir.sign.v1.SignWithOIDC.
 * Use `create(SignWithOIDCSchema)` to create a new message.
 */
export const SignWithOIDCSchema = /*@__PURE__*/
  messageDesc(file_agntcy_dir_sign_v1_sign_service, 2);

/**
 * Describes the message agntcy.dir.sign.v1.SignWithOIDC.SignOpts.
 * Use `create(SignWithOIDC_SignOptsSchema)` to create a new message.
 */
export const SignWithOIDC_SignOptsSchema = /*@__PURE__*/
  messageDesc(file_agntcy_dir_sign_v1_sign_service, 2, 0);

/**
 * Describes the message agntcy.dir.sign.v1.SignWithKey.
 * Use `create(SignWithKeySchema)` to create a new message.
 */
export const SignWithKeySchema = /*@__PURE__*/
  messageDesc(file_agntcy_dir_sign_v1_sign_service, 3);

/**
 * Describes the message agntcy.dir.sign.v1.SignResponse.
 * Use `create(SignResponseSchema)` to create a new message.
 */
export const SignResponseSchema = /*@__PURE__*/
  messageDesc(file_agntcy_dir_sign_v1_sign_service, 4);

/**
 * Describes the message agntcy.dir.sign.v1.VerifyRequest.
 * Use `create(VerifyRequestSchema)` to create a new message.
 */
export const VerifyRequestSchema = /*@__PURE__*/
  messageDesc(file_agntcy_dir_sign_v1_sign_service, 5);

/**
 * Describes the message agntcy.dir.sign.v1.VerifyResponse.
 * Use `create(VerifyResponseSchema)` to create a new message.
 */
export const VerifyResponseSchema = /*@__PURE__*/
  messageDesc(file_agntcy_dir_sign_v1_sign_service, 6);

/**
 * SignService provides methods to sign and verify records.
 *
 * @generated from service agntcy.dir.sign.v1.SignService
 */
export const SignService = /*@__PURE__*/
  serviceDesc(file_agntcy_dir_sign_v1_sign_service, 0);

